# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog-sql:
    image: mcr.microsoft.com/azure-sql-edge:latest

  rabbitmq:
    image: rabbitmq:management
