version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - hermes

  catalog-sql:
    container_name: catalog-sql
    restart: on-failure:3
    hostname: catalog-sql
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: ${CATALOG_API_MSSQL_SA_PASSWORD}
      ACCEPT_EULA: 1
      MSSQL_PID: Developer
    networks:
      - hermes

  basket-redis:
    container_name: basket-redis
    restart: on-failure:3
    hostname: basket-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - hermes

  order-mongodb:
    container_name: order-mongodb
    restart: on-failure:3
    hostname: order-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ORDER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ORDER_MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - hermes

  payment-sql:
    container_name: payment-sql
    restart: on-failure:3
    hostname: payment-sql
    ports:
      - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: ${CATALOG_API_MSSQL_SA_PASSWORD}
      ACCEPT_EULA: 1
      MSSQL_PID: Developer
    networks:
      - hermes

  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:latest
    restart: on-failure:3
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
      SQLPAD_AUTH_DISABLED: True
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: admin
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__catalog__name: SQL Server Catalog
      SQLPAD_CONNECTIONS__catalog__driver: sqlserver
      SQLPAD_CONNECTIONS__catalog__host: catalog-sql
      SQLPAD_CONNECTIONS__catalog__database: master
      SQLPAD_CONNECTIONS__catalog__username: ${CATALOG_API_MSSQL_USERNAME}
      SQLPAD_CONNECTIONS__catalog__password: ${CATALOG_API_MSSQL_SA_PASSWORD}
    volumes:
      - sqlpad-volume:/var/lib/sqlpad
    depends_on:
      - catalog-sql
    networks:
      - hermes

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ORDER_MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ORDER_MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ORDER_MONGO_INITDB_ROOT_USERNAME}:${ORDER_MONGO_INITDB_ROOT_PASSWORD}@order-mongodb:27017/
    depends_on:
      - order-mongodb
    networks:
      - hermes

volumes:
  sqlpad-volume:

networks:
  hermes:
    name: hermes
