apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project }}-{{ .Values.environmentTag }}
  labels:
    name: {{ .Values.project }}-{{ .Values.environmentTag }}
    environment: {{ .Values.environmentTag }}
    release: {{ .Release.Name }}
