apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project }}-{{ .Values.environmentTag }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Values.project }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    name: {{ .Values.project }}-{{ .Values.environmentTag }}
    environment: {{ .Values.environmentTag }}
