apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: {{ .Values.project }}-{{ .Values.environmentTag }}
spec:
  selector:
    app: catalog-api
    tier: backend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.catalogApi.service.nodePort }}
