apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: {{ .Values.project }}-{{ .Values.environmentTag }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Values.project }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app: catalog-api
    tier: backend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.catalogApi.service.nodePort }}
